### ISSUE TITLE
Refactoring: consider replacing common api logic with pwned gem

### ISSUE THREAD

**Issue by michaelbanfield** [michaelbanfield/devise-pwned_password#11]
It probably makes sense to move the common api logic to a separate gem, there are a few out there including

https://github.com/philnash/pwned

Blocker for this would be if the pwned gem doesnt give us a way to implement custom URL/blob storage support. At first glance it looks like this might work as there are S3 adapters for open uri.

**Comment by philnash** [comment]
Hey! I was just looking through this and wondered if it would be a good idea to suggest replacing the guts of this with the [pwned gem](https://github.com/philnash/pwned).

What do you mean by custom URL/blob storage support though? Is that in regard to #10? I'm happy to discuss or make updates to the gem to help this along.

**Comment by michaelbanfield** [comment]
Hey, so im not as keen on the blob storage idea anymore but essentially I planned to support custom url's for the api endpoint, and then create a updated version of something like this https://github.com/eterps/open-uri-s3 to support passing in an "s3://mypwnedpasswordsapi" style url. 

This would let people just push the dataset up to a bucket with each prefix as a key, and then get their own version of the api without worrying about availability issues or security concerns with calling the actual api.

I want to avoid adding aws sdk dependancies to either this gem or the pwned gem so probably need to think of a better way.

**Comment by michaelbanfield** [comment]
Resolved by #13 and published to rubygems https://rubygems.org/gems/devise-pwned_password/versions/0.1.5

**Comment by philnash** [comment]
It would be easy enough to allow configuring a custom URL to be used. I guess it’s better not to build features like the s3 storage before someone asks for it! If it does come up, I’d look into some sort of dependency injection so we could avoid aws library dependencies in either this or the pwned gem.
