### ISSUE TITLE
Feature: Ability to disable pwned check in test environment

### ISSUE THREAD

**Issue by AL-Outpost** [michaelbanfield/devise-pwned_password#18]
Great gem! But one issue I noticed is that it was flagging my "test" users in Rspec as having pwned passwords. Which they did -- but I don't want/need to call the API for each test case, and in fact it slows down my test suite by almost 3x.

Currently I'm working around the issue as such: 
```
class User < ApplicationRecord
  if Rails.env.test?
    devise :invitable ...  :validatable, :lockable
  else
    devise :invitable ... :validatable, :lockable, :pwned_password
  end
```

Which feels wrong! But it works. If there were some way to disable the check in the test environment by config, that'd be amazing.

**Comment by kamen-hursev** [comment]
You can achieve this without the duplication like so:
```
class User < ApplicationRecord
  devise :invitable ...  :validatable, :lockable
  devise :pwned_password unless Rails.env.test?
end
```

**Comment by AL-Outpost** [comment]
Oh that's way cleaner. Thanks!

**Comment by michaelbanfield** [comment]
Thanks for reporting.

I suspect there is a few situations where people would expect the API to keep working in the test environment (and want to avoid a backwards incompatible change).

So instead of disabling it in the module I've added the snippet above to the README.
