### ISSUE TITLE
Pwned Passwords API will continue to be free, so this gem is not affected by the changes to the HIBP API

### ISSUE THREAD

**Issue by ndbroadbent** [michaelbanfield/devise-pwned_password#19]
I was reading [this article](https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/) about upcoming changes to the HIBP API, where API access is now going to cost $3.50 per month. I was initially worried that the Pwned Passwords API would be included in these changes, but this API will still be free:

> One important distinction: this doesn't apply to the APIs that don't pull back information about an email address; the API listing all breaches in the system, for example, is not impacted by any of the changes outlined here. It can be requested with version 3 in the path, but also with previous versions of the API. Because it returns generic, non-personal data it doesn't need to be protected in the same fashion (plus it's really aggressively cached at Cloudflare). **Same too for Pwned Passwords - there's absolutely zero impact on that service.**

I was about to open an issue on this repo to talk about upgrading to the v3 API, in case we needed to make some changes. But I thought I may as well open an issue anyway, in case other people are worried about it, and didn't realize that the Pwned Passwords will not be affected.

Maybe it could make sense to add a note to the README about this?

**Comment by michaelbanfield** [comment]
Good idea, added a note to the README.
